### ISSUE TITLE
how to start a website stream

### ISSUE THREAD

**Issue by fatpunkybearass** [esp-arduino-libs/ESP32_USB_Stream#5]
Hi, thanks for the work making this library for arduino ide, really saves me a lot of trouble working on vscode platform. 

So a small question: how do I start a website stream with this uvc code? There is website uvc stream code in esp-iot solution, but that is for vscode and I still failed to make it work, so I want to ask this here because Im more familiar with arduino ide. Thanks!

**Comment by Lzw655** [comment]
Hi @fatpunkybearass, thank you for using the library! 

I believe the website UVC stream code in the esp-iot solution needs to be modified before it can be ported for use in the Arduino IDE. However, this is not currently part of our development plans. We will consider implementing it in the future, and any updates will be shared here.

**Comment by fatpunkybearass** [comment]
hi zhongwei
我的意思是有没有可能在arduino ide里的这个ESP32_USB_Stream库的示例代码中加入能直接在网页上显示视频的功能，如果这不在你们的计划中那就算了。如果这对于你们很容易，那不妨加入这个功能，对于我这样的新手是一个比较大的帮助。谢谢！
Is it possible to add the function of displaying video directly on the web page to the sample code of the ESP32_USB_Stream library in the Arduino IDE? If this is not in your plan, it is fine. If this is very easy for you, then maybe you could consider adding this function, which is a great help for thousands of beginners like me.
thanks!

**Comment by Lzw655** [comment]
非常抱歉，这个库仅用于提供与 USB 直接相关的功能，但是我们会考虑将 “在网页上显示视频的功能” 单独封装成一个新的库，然后通过示例的形式将两者结合起来使用。

**Comment by fatpunkybearass** [comment]
好的好的，谢谢啦

**Comment by jiesou** [comment]
所以现在有消息了吗
esp-idf 平台上有很多 example
https://github.com/espressif/esp-iot-solution/tree/master/components/usb/usb_stream

https://github.com/espressif/esp-iot-solution/tree/master/examples/usb/host/usb_camera_lcd_display
那 platformio 啥时候轮到呢

**Comment by jiesou** [comment]
自己折腾好久都没折腾出来哦

**Comment by fatpunkybearass** [comment]
> 自己折腾好久都没折腾出来哦

据我现在的已有经验，他们的code很挑摄像头。我现在已经放弃使用esp32s3做这个项目，改成树莓派zero2w了。用esp32处理摄像头数据不管如何，帧的大小和帧率都受限。用手机显示uvc摄像头的画面轻轻松松。
